lib/components/Tabs/Tab.tsx, lib/components/Tabs/TabTitle.tsx, lib/components/Tabs/Tabs.tsx
Changes:
- added onClickHandler as an optional props 
- the tab panel is now optional so this component can be use as both `Tab` and `SwitcherItem`
=> [FEQ] Shayan/FEQ-1503/Refactor: made tab panel optional

lib/components/Input/HelperMessage.tsx, lib/components/Input/Input.scss, lib/components/Input/index.tsx, lib/main.ts
Created Input component with base stylings.
This input component can be extended to Text field, Password Field and Text Area.
It currently has these states: `active` & `disabled`.
It currently has these variants: `general`, `success` & `error`.
It comes with `HelperMessage` where based on the variant or the state of the input component it will change its color.
It has the option to pass text or icon on the right side of the input.
It is uncontrolled so you can use any third party libraries.   
https://github.com/deriv-com/ui/assets/103104395/c158e049-23f9-4ae9-b533-edfa5132a353
=> Aizad/FEQ-1442/Input Component

package.json, vite.config.ts
This fixes the imports so we can import components from the root, and still get the type definitions.
Example:
`import { Button } from '@deriv-com/ui'`
=> Mark/Shayan/build: removed dist from import path

lib/components/Dropdown/Dropdown.scss, lib/components/Dropdown/index.tsx, lib/components/Input/index.tsx, lib/components/Text/index.tsx, package-lock.json, package.json, src/main.tsx, src/stories/Dropdown.stories.ts
Added a dropdown component within the deriv/ui package, making it accessible for use across various packages by importing it directly from this library.
=> [FEQ]Yaswanth/FEQ-1440/Added Dropdown component

lib/components/PasswordInput/PasswordMeter.scss, lib/components/PasswordInput/index.tsx, src/stories/PasswordInput.stories.tsx
- Improve PasswordInput for Storybook
- Edit styles for PasswordInput
- Add types for PasswordInput component
=> Aizad/ Improvement for Password Input

lib/components/Input/HelperMessage.scss, lib/components/Input/Input.scss, lib/components/Input/index.tsx, src/stories/Input.stories.tsx
- Adding Storybook for Input component
- Made style changes to Input and HelperMessage classes
=> Aizad/ Adding Storybook to Input component

lib/components/InlineMessage/InlineMessage.scss, lib/components/InlineMessage/VariantIcons.tsx, lib/components/InlineMessage/index.tsx, lib/main.ts, src/stories/InlineMessage.stories.ts
- Added Inline Message inside of UI
- Inline Message has variants: `info`, `success`, `warning` & `error`
- Inline Message has types: `filled`, `outlined`
- Accepts props: `className`, `variant`,`type`, `children` and `Icon`
=> Aizad/FEQ-1660/Added Inline Message

lib/components/Checkbox/Checkbox.scss, lib/components/Checkbox/index.tsx, lib/main.ts, src/stories/Checkbox.stories.tsx
- Exported `<Divider />` component
- Sort component alphabetically inside of `main.ts`
- Fix issue when it is disabled checked should not be able to change onClick
- Updated storybook to reflect changes on the component
https://github.com/deriv-com/ui/assets/103104395/cb1a6152-f4f5-4b08-912b-67f224dd8c2a
=> fix: Improve the usability for Checkbox component

lib/components/PageLayout/PageLayout.scss
Changes:
Removed the padding-top for the PageLayout and also the gap between the sidebar and content section.
https://github.com/deriv-com/ui/assets/125039206/cb1c557f-c894-4599-b66b-d14c8c9a12d2
=> [FEQ] aum/FEQ-1696/page-layout-remove-padding-gap

lib/components/ActionScreen/ActionScreen.scss, lib/components/ActionScreen/index.tsx, src/stories/ActionScreen.stories.tsx
ActionScreen is a reusable component which is used in the cashier and accounts-settings pages for showing screens with design containing the following layout:
```
icon
title
Description
CTA (optional)
```
=> [FEQ] Aum/FEQ-1699/ActionScreen-component

lib/components/TextArea/TextArea.scss, lib/components/TextArea/index.tsx, lib/components/ToggleSwitch/index.tsx, src/stories/TextArea.stories.ts
Added a textarea component within the deriv/ui package, making it accessible for use across various packages by importing it directly from this library.
=> [FEQ]Yaswanth/FEQ-1448-Added Text Area Component

lib/components/VerticalTab/VerticalTab.scss, lib/components/VerticalTab/VerticalTabItem.tsx
- fix active tab highlighting
- remove extra outer padding
=> Vertical tab improvement

lib/components/Checkbox/index.tsx, src/stories/Checkbox.stories.tsx
- remove useId() from Checkbox component.
- make `name` as a required prop.
- use `name` instead as a fallback for the `id`.
- updated storybook.
=> Aizad/ Fix Checkbox id returning errors inside of deriv.app

vite.config.ts
changes: 
- `dts({ include: ['lib'], exclude: ['lib/**/*.spec.tsx'] })`
- `glob.sync("lib/**/*.{ts,tsx}", { ignore: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx", "**/__tests__/**"]`
=> build: excluded test files from build process

lib/components/Modal/Modal.scss
changes:
- removed the default padding from modal body to let the consumer apply it if needed
- added `overflow: auto` to modal body wrapper
=> fix: fixed oveflow issue in modal body

lib/components/Modal/Modal.scss, lib/components/Modal/ModalHeader.tsx
- when no title is passed the close icon inside modal header was left aligned but we expected that it be right
- added a new classname and check if there is no children passed to the header, then I'm applying `flex-end` for the `justify-content`
before: 
after:
=> fix: added new classname to modal header

lib/components/Button/__test__/Button.spec.tsx, lib/components/Button/index.tsx
Add unit tests for the Button component.
=> chore: add unit tests for button

lib/components/Checkbox/__test__/Checkbox.spec.tsx
Add some unit tests for the Checkbox component.
=> chore: add tests for checkbox

src/components/Loader/__test__/Loader.spec.tsx
Added test cases for loader component in deriv-com/ui library
=> [FEQ]Yaswanth/FEQ-1972 Added Test cases for Loader component

src/components/InlineMessage/__test__/InlineMessage.spec.tsx
Added Test cases for inline message component
=> [FEQ]Yaswanth/FEQ-1995 Added Test for inline message component

src/components/PageLayout/__test__/PageLayout.spec.tsx, src/hooks/useDevice.ts
Adding new check for tablet view
=> Farhan/add isTabletPortrait to useDevice

src/components/Accordion/index.tsx, src/components/Dropdown/index.tsx, src/components/PasswordInput/index.tsx, src/components/SideNote/index.tsx, src/components/Tabs/TabTitle.tsx
When Accordion component is used inside a form, due to event bubbling the form submit handler gets invoked. This is because for most browsers the default type of button is `submit`.
The issue is seen in Accordion and SideNote component
The button type is set to `button` to avoid this
=> likhith/fix: button type in accordion component

src/components/AppLayout/Header/DerivLogo/index.tsx, src/components/AppLayout/Header/index.tsx, src/components/AppLayout/__test__/DerivLogo.spec.tsx, stories/DerivLogo.stories.tsx
This PR contains DerivLogo component in the app.deriv nav.
It accepts 2 different variants for default header and wallets header.
=> Niloofar/Deriv Logo component

src/components/Table/index.tsx, src/hooks/useFetchMore.ts, stories/Table.stories.tsx
- There were issues with the data being infinitely fetched because it had assumed the user had reached the end of the scrollbar height. Thus I had fixed it here in this PR
=> Ameerul / Fix useFetchMore loadMore data issues on scroll

src/components/Dropdown/Dropdown.scss, src/components/Dropdown/index.tsx, src/components/Input/Input.scss, src/components/Input/index.tsx, stories/Dropdown.stories.ts
=> Lubega / Fix dropdown UI discrepancies

src/components/Button/Button.scss, src/components/Button/index.tsx, stories/Button.stories.ts
- Added `borderWidth` prop and it's variants (`none`, `sm`, `md`)
=> [FEQ] Jim/FEQ-2472/add border width prop and variants

src/components/Tooltip/Tooltip.scss, src/components/Tooltip/index.tsx, stories/Tooltip.stories.tsx
- Replaced Tooltip position from `auto` to `top`
- Added new prop for hide tooltip
- Updated storybook component
=> Aizad/FEQ-2469/Improved Tooltip 

src/components/AppLayout/LanguagesSwitcher/LanguagesModal.scss
- changed language items height to `auto` and added padding-y 
- changed the margin-x to `auto` for the modal container
=> style: fixed style issues for language switcher modal

src/components/Text/index.tsx
Added colours `black`, `orange`, and `system-dark-2-general-text` to the `TextColors` prop type
=> [FEQ] Jim/FEQ-2508/Add colours to prop type

package-lock.json, package.json, src/hooks/useFetchMore.ts
- Added debounce so it doesn't spam loadMore as there are brief moments where it will constantly spam loadMore instead of waiting for it to finish.
https://github.com/user-attachments/assets/59e8255f-0369-46b2-a502-a628a9de3b75
https://github.com/user-attachments/assets/b8afcddd-b1ed-491f-b98a-753a1c543eee
https://github.com/user-attachments/assets/bbf97ddd-bd07-4e95-9fce-3862a642663a
=> Ameerul / Fix multiple api calls when scrolling table

src/components/AppLayout/Notifications/Notification.tsx, src/components/AppLayout/Notifications/__test__/notification.spec.tsx, src/components/AppLayout/Notifications/index.tsx, src/components/AppLayout/Notifications/types.ts, stories/Notifications.stories.tsx
Some notifications will not require a button to be shown, so change it to be optional.
=> feat: make action in notification optional

src/components/Dropdown/index.tsx, stories/Dropdown.stories.ts, stories/Dropdown.stories.tsx
Currently the dropdown component doesn't accept any prop for dropdown icon and takes the chevron as default. But there are cases where search icon / ellipsis is needed for the dropdowns. This PR adds a dropdownIcon prop to the component, so if the icon is passed, the passed icon will be taken, or else it defaults to chevron
=> fix: add dropdown icon prop

src/components/AppLayout/Notifications/index.tsx
fix: remove the method that closes the modal upon clicking on the button "clear all"
Since the main application notifications do not close the modal window by clicking on the “clear all” button and in the bot annonces we need the same approach, I propose to remove this line in general
=> [BOT]maryia/fix: remove the method that closes the modal upon clicking on the button clear all

src/components/Accordion/Accordion.scss, src/components/Accordion/index.tsx
- Currently, the accordion component is not able to be scrolled to by whoever consumes it. Now users can pass a ref to the accordion, and a function to the component.
- The new function `onScrollToAccordion` which is optional, and it should be handled by the consumer as for my case, I needed the accordion to be scrolled to the top of the page, and this needs to be handled by the main div that surrounds all of my accordions.
- Also I changed the overflow value to scroll as using auto will add the scrollbar to the content as it opens, which causes it to shift the content. Scroll will already add it by default, and won't cause a shift.
https://github.com/user-attachments/assets/ebf7a187-08ff-41e4-ad33-988c1edd8c81
https://github.com/user-attachments/assets/fa536280-7920-4d02-be18-e782b5f9e6ee …
=> Ameerul / Add Scroll To Accordion Functionality

src/components/Breadcrumbs/Breadcrumbs.scss, src/components/Breadcrumbs/__tests__/Breadcrumbs.spec.tsx, src/components/Breadcrumbs/index.tsx, src/main.ts, src/styles/base/_root.scss, stories/Badge.stories.tsx, stories/Breadcrumbs.stories.tsx
- Implement Breadcrumbs Component
- Add test for Breadcrumbs Component
- Add story for Breadcrumbs Component
=> [FEQ] george / FEQ-2683 / Implement Breadcrumbs Component

src/components/Breadcrumbs/Breadcrumbs.scss, src/components/Breadcrumbs/index.tsx, src/styles/abstracts/_layout.scss, src/styles/index.scss
1. When we are passing separator prop as `separator={is_rtl && <LegacyChevronLeft1pxIcon />}` nothing is rendering because of `??` operator.
Fix it using `||` operator instead.
2. Minor fix for hover state and style
3. Add RTL mixin
=> [FIX] Separator visibility

src/components/Breadcrumbs/Breadcrumbs.scss, src/components/Breadcrumbs/index.tsx, src/components/Text/Text.scss
Resolve color issues caused by race conditions in the bundled CSS.
After bundling deriv-com/ui in deriv-app, the CSS of the Text component is overriding my custom styles in the Breadcrumbs component, even though the custom className in Text is defined after the base `deriv-text` classes. 
This can be addressed by directly passing the color prop to the Text component instead of relying on external style overrides.
=> fix: :ambulance: fix colors in Breadcrumbs

src/components/AppLayout/AccountSwitcher/AccountsItem/__test__/AccountsItem.spec.tsx, src/components/AppLayout/AccountSwitcher/AccountsItem/index.tsx, src/components/Button/Button.scss, src/components/Button/index.tsx, stories/Button.stories.ts
- Added a new prop called `onResetBalance` to <AccountSwitcher.AccountsItem/>. when passed to the component it will render a button with `Reset balance` label instead of the account's balance number
- Added a new size `xs` to <Button/> component which is used in reset balance button
- Added new test cases for `<AccountSwitcher.AccountsItem/>`
=> Feat: Updated AccountSwitcher and Button Components
