- lib/components/Button/index.tsx
- lib/components/Loader/index.tsx
- lib/components/Text/index.tsx
- package-lock.json
- package.json
- vite.config.ts
added `classnames`  props to all components
> feat: added classname prop to components

- lib/components/Tabs/Tab.tsx
- lib/components/Tabs/Tabs.tsx
Changes: 
- Added className to `<Tab/>` component
> Shayan/ refactor:added classname to Tab component

- lib/components/Tabs/Tab.tsx
- lib/components/Tabs/TabTitle.tsx
- lib/components/Tabs/Tabs.tsx
- src/main.tsx
changes: 
- added onChange to Tabs component . it's using the tab index number to determine which tab item should be targeted.
> Shayan/ fix: add onChange to Tabs component

- package-lock.json
- package.json
changes: 
- updated vite to the latest version
> bump to verison 0.0.1-beta.8

- lib/components/Tabs/Tabs.tsx
FIx: 
- added useEffect to update `activeTab` if it's is passed dynamically from the consumer side
> fix: added useEffect for activeTab in Tabs component

- package-lock.json
- package.json
changes: 
- fixed bug in Tabs component
> build: bump to version 0.0.0-beta.9

- .github/workflows/publish_npm_package.yml
- .github/workflows/test_workflow.yml
- package-lock.json
- package.json
- release.config.js
- release.utils.js
This is to add auto publish strategy to npm using semantic-release npm package.
> Ako/ add auto publish to npm action

- lib/components/ToggleSwitch/ToggleSwitch.scss
- lib/components/ToggleSwitch/index.tsx
- lib/main.ts
- src/stories/ToggleSwitch.stories.ts
Added a toggle component within the deriv/ui package, making it accessible for use across various packages by importing it directly from this library.
> [FEQ]Yaswanth/FEQ-1439/Added Toggle Component

- lib/main.ts
changes: 
- exported `Dropdown` component
- exported `useDevice` and `useOnClickOutside` hooks
> fix: exported missing components and hooks

- lib/components/Tabs/TabTitle.tsx
- lib/components/Tabs/Tabs.tsx
changes: 
- added TitleFontSize Props so we can control tabs title font size
> chore: added TitleFontSize to Tabs component

- lib/components/Text/Text.scss
- lib/components/Tooltip/Tooltip.scss
- Remove default text styling in Tooltip
- Convert Text component units from rem to px
> Aizad/Tooltip Fix

- lib/components/Input/Input.scss
- lib/components/Input/index.tsx
- Updated Input styling by wrapping a container.
- Updated default color style.
- Added hover color.
> fix: update minor input styles

- lib/components/Checkbox/Checkbox.scss
- lib/components/Checkbox/checkbox-icon.svg
- lib/components/Checkbox/index.tsx
- lib/main.ts
- src/stories/Checbox.stories.tsx
- src/stories/Checkbox.stories.tsx
- Added Checkbox component
- Inherits all of the input from HTML Input
- Has different states: `checked`, `unchecked`, `disabled`, `error`
- Styles can be overwritten with `className`, `wrapperClassName` and `labelClassName`
> Aizad/Checkbox Component

- lib/components/Input/HelperMessage.scss
- lib/components/Input/Input.scss
- lib/components/Input/index.tsx
- lib/components/PasswordInput/PasswordInput.scss
- src/stories/Input.stories.tsx
- src/stories/PasswordInput.stories.tsx
Issue: 
Solved:
- fix misalignment of Password Strength Bar inside of `PasswordInput`
- fix width of helper message in `Input` component
- made styling changes inside `PasswordInput` and `Input`
- added more props such as `hideMessage` to `Input` and `PasswordInput`
- updated storybook
> Aizad/Fix Password Input Meter Issue

- lib/components/Divider/index.tsx
- src/stories/Divider.stories.tsx
Added Divider component
Accepts 3 props: 
- `variant` which can be "horizontal" | "vertical"
- `color`
- `margin`
> Niloofar/FEQ-1661/Divider Component

- lib/components/Input/HelperMessage.scss
- lib/components/Input/Input.scss
- lib/components/Input/index.tsx
- lib/components/PasswordInput/PasswordInput.scss
- lib/components/PasswordInput/index.tsx
- src/stories/Input.stories.tsx
- src/stories/PasswordInput.stories.tsx
- added fixed height to helper message placeholder under input
- added `isFullWidth` prop to Input component
> Aizad/FEQ-1690/Fix Input Issues - Helper Message, Width

- lib/components/PasswordInput/PasswordInput.scss
- lib/components/PasswordInput/index.tsx
- src/stories/PasswordInput.stories.tsx
- updated z-index inside of PasswordInput 
- updated storybook component based on the changes made
> Aizad/Password Input Fix

- lib/components/VerticalTab/CollapsibleVerticalTabItem.tsx
- lib/components/VerticalTab/VerticalTabItem.tsx
- lib/components/VerticalTab/VerticalTabItems.tsx
Changes:
- to resolve the issues with translations for tab Item I have added `id` with type `string` and added `React.JSX.Element` to `title`
- The default font size of tab items has been adjusted to `14px` to align with the design file.
> fix: added id to vertical-tab props 

- lib/main.ts
A small PR to export `ActionScreen` component.
> [FEQ] aum/export-action-screen

- lib/components/Button/index.tsx
- src/stories/Button.stories.ts
> thisyahlen/chore: expose all props to button

- lib/components/Table/Table.scss
- lib/components/Table/index.tsx
- lib/hooks/useFetchMore.ts
- lib/main.ts
- package-lock.json
- package.json
- src/stories/Table.stories.tsx
Table component using tanstack react/table + storybook
> feat: added the table component

- lib/components/Checkbox/Checkbox.scss
- lib/components/Checkbox/index.tsx
- Width is shrinking in mobile screen
- Position of the checkbox is not according to design
- Minor stylings improvement
> Aizad/FEQ-1734/Fix Checkbox Issue

- lib/components/Dropdown/Dropdown.scss
Used Px instead of rem as it is standard now
> [FEQ]Yaswanth/FEQ-1746_Use-px-instead-of-rem

- lib/components/Dropdown/index.tsx
The variant name for the prompt needs to be changed so that we can type in the input box.
> [FEQ]Yaswanth/FEQ-1745/Need-to-fix-variant-names

- lib/components/TextArea/TextArea.scss
- lib/components/TextArea/index.tsx
- lib/main.ts
- src/stories/TextArea.stories.tsx
- exported `TextArea` component inside of `main.tsx` file.
- refactor `TextArea` component and minor styles modification.
- updated Storybook for `TextArea` 
**Without Counter**
https://github.com/deriv-com/ui/assets/103104395/89af8486-a909-4420-8d29-fea305f5e533
**With Counter**
https://github.com/deriv-com/ui/assets/103104395/98fd8410-1ed1-4aaf-ae27-fba53834640c
> Aizad/ FEQ-1828/Textarea improvments

- lib/components/Button/Button.scss
- lib/components/Button/index.tsx
- src/stories/Button.stories.ts
- Refactor Button components
- Updated styles for Button components
- Button components supports variants in all different colors
- Updated Storybook with the changes
> Aizad/FEQ-1502/Adding New Variants inside of Button

- .github/workflows/publish_npm_package.yml
> Revert "ci: replaced CI_GITHUB_TOKEN with GITHUB_TOKEN"

- lib/styles/abstracts/_typography.scss
- lib/styles/abstracts/_variables.scss
- lib/styles/base/_root.scss
- lib/styles/index.scss
- Replace existing values from `rem` to `px`.
- Made minor changes inside of style `directory`
> Aizad/ Change root stylings from rem to px

- lib/components/ActionScreen/__test__/ActionScreen.spec.tsx
Add unit tests for the ActionScreen component.
> chore: add unit tests for ActionScreen

- .github/workflows/publish_npm_package.yml
- package.json
this is to remove the extra steps of automation as they have security concerns.
> Ako/ to create the release tag manually

- package-lock.json
- package.json
- release.config.cjs
No git pushing is needed anymore
> chore: remove git pushing from semantic release

- lib/components/Text/Text.scss
- lib/components/Text/index.tsx
- lib/styles/base/_root.scss
- src/stories/Text.stories.ts
Changes:
- added support for white color in text component
> chore: added white color to text component

- src/components/Table/Table.scss
- src/components/Table/index.tsx
- added emptyMessage prop to the Table component
> Ameerul / FEQ-1747 / Add empty message prop to Table component

- README.md
- package.json
changes:
- removed unnecessary commands from package.json
- updated readme file
> docs: updated readme file

- src/components/Dialog/__test__/Dialog.spec.tsx
> test: fixed failed tests for Dialog

- src/components/TextArea/__test__/TextArea.spec.tsx
Added test cases for text area component
> [FEQ]Yaswanth/FEQ-1934-Added test cases for textarea component

- src/components/Text/__test__/Text.spec.tsx
Added test cases for text component
> [FEQ]Yaswanth/FEQ-1933_Added test for text component

- src/components/Tooltip/__test__/Tooltip.spec.tsx
Added test cases for tooltip component in deriv-com/ui library
> [FEQ]Yaswanth/FEQ-1982_Added test cases for tooltip component

- package-lock.json
- package.json
move react modal types to dependencies
> Thisyahlen/chore: move react modal types to dependencies

- src/components/PageLayout/__test__/PageLayout.spec.tsx
Added test cases for page layout component
> [FEQ]Yaswanth/FEQ_1996 Added test for page layout component

- src/components/PasswordInput/PasswordConstants.ts
- src/components/PasswordInput/PasswordMeter.tsx
- src/components/PasswordInput/PasswordUtils.ts
- src/components/PasswordInput/index.tsx
- stories/PasswordInput.stories.tsx
changes: 
- Added CustomErrorMessage prop to `PasswordInput`
- Added new score value
- Updated the `validatePassword` function 
- Added new story to cover this scenario
> [FEQ] / Shayan/ FEQ-2122 / add custom error message to passwordInput component

- src/components/AppLayout/Footer/Footer.scss
- src/components/AppLayout/Footer/index.tsx
- src/components/AppLayout/Header/Header.scss
- src/components/AppLayout/Header/index.tsx
- src/components/AppLayout/Wrapper/Wrapper.scss
- src/components/AppLayout/Wrapper/index.tsx
- src/components/AppLayout/__test__/Footer.spec.tsx
- src/components/AppLayout/__test__/Header.spec.tsx
- src/components/AppLayout/__test__/Wrapper.spec.tsx
- src/components/AppLayout/index.ts
- src/main.ts
- stories/Footer.stories.tsx
- stories/Header.stories.tsx
- stories/Wrapper.stories.tsx
This PR contains:
- Header Wrapper
- Footer Wrapper
- Wrapper (Left | Right)
> Niloofar/Added App Layout Wrappers

- src/components/Accordion/__test__/Accordion.test.tsx
- src/components/Accordion/index.tsx
changes: 
added classname and other valid props to accordion
> chore: added classname and other valid props to accordion component

- src/components/ContextMenu/ContextMenu.scss
changes:
- removed basic paddings, margins, width and height
> chore: removed basic paddings and margins from contextmenu wrapper

- package-lock.json
- package.json
- playground/index.tsx
- src/components/AppLayout/MenuItem/index.tsx
- src/components/AppLayout/TooltipMenuIcon/TooltipMenuIcon.scss
- src/components/AppLayout/TooltipMenuIcon/__test__/TooltipMenuIcon.spec.tsx
- src/components/AppLayout/TooltipMenuIcon/index.tsx
- src/components/AppLayout/index.ts
- src/main.ts
- stories/TooltipMenuIcon.stories.tsx
A component that renders a `button` | `a` | `div` with a tooltip.
> Niloofar/ TooltipMenuIcon component

- playground/index.tsx
- src/components/AppLayout/AccountSwitcher/AccountSwitcher.scss
- src/components/AppLayout/AccountSwitcher/AccountsItem/__test__/AccountsItem.spec.tsx
- src/components/AppLayout/AccountSwitcher/AccountsItem/index.tsx
- src/components/AppLayout/AccountSwitcher/__test__/AccountSwitcher.spec.tsx
- src/components/AppLayout/AccountSwitcher/index.tsx
- src/components/AppLayout/AccountSwitcher/types.ts
changes:
- added `isDiabled` prop to account switcher to control the drop down
- fixed some style issues 
- updated TAccount type structure
> chore: added isDisabled to account switcher component

- src/components/AppLayout/AccountSwitcher/AccountSwitcher.scss
changes: 
- updated account-switcher font size in mobile
> chore: fixed minor style issue in account switcher

- src/components/AppLayout/AccountSwitcher/AccountSwitcher.scss
- src/components/AppLayout/Notifications/index.scss
- src/components/AppLayout/Notifications/index.tsx
- src/components/AppLayout/Notifications/types.ts
- src/components/AppLayout/TooltipMenuIcon/index.tsx
changes:
- added support to pass props like className,... to `Notifications` 
- fixed minor style issues in `Notifications`
- added `tooltipClassName` to `TooltipMenuIcon`
> fix: fixed style issues in tooltip and notification components

- src/components/AppLayout/AccountSwitcher/AccountSwitcher.scss
- src/components/AppLayout/PlatformSwitcher/PlatformSwitcher.scss
changes:
- fixed minor style issues in accountSwitcher and PlatformSwitcher
> fix: fixed minor style issues

- src/components/AppLayout/PlatformSwitcher/PlatformSwitcher.scss
- src/components/AppLayout/PlatformSwitcher/PlatformSwitcherItem.tsx
It turns out we've been using the wrong design guide for our platform switcher. I've fixed the problems by making a pull request.
> Niloofar/ Fixed Platform Switcher style issues

- src/components/AppLayout/Submenu /Submenu.scss
- src/components/AppLayout/Submenu /__tests__/Submenu.spec.tsx
- src/components/AppLayout/Submenu /index.tsx
- src/components/AppLayout/index.ts
- src/main.ts
- stories/Submenu.stories.tsx
https://github.com/deriv-com/ui/assets/93518187/4ce5d14c-67c0-4abd-a02d-0ca654a82124
> Niloofar/ Submenu component

- src/components/Dropdown/index.tsx
- stories/Dropdown.stories.ts
if shouldsetvalue is enabled, clear the field value everytime the list changes(selected item is not present in the dropdown)
Before :
https://github.com/deriv-com/ui/assets/122768621/8cd70d70-7303-4abc-b14d-921eafaedd35
After 
https://github.com/deriv-com/ui/assets/122768621/e8ccf537-6cda-48d7-9e23-9833125c69a3
No Search results
https://github.com/deriv-com/ui/assets/122768621/4956fd83-45c3-4d4a-86ae-5392e30e3369
> Nada/fix: clear field value when list changes

- src/components/Button/Button.scss
- src/components/Button/index.tsx
- stories/Button.stories.ts
- Added the colour `#ff444f14` for the primary variant on hover
> [FEQ] Jim/FEQ-2490/add transparent red color

- src/components/Dropdown/index.tsx
- Added a condition inside of the Input Field when there is an error message the dropdown should show the error variant.
> Aizad/Fix for showing error variant inside of Dropdown

- .github/workflows/coveralls.yml
- .github/workflows/publish_npm_package.yml
- .github/workflows/test_workflow.yml
- updated the target branch from `main` to `master` in the gh workflows
> ci: updated the target branch to master in workflows

- src/components/PageLayout/__test__/PageLayout.spec.tsx
- src/hooks/useDevice.ts
- src/styles/abstracts/_devices.scss
* added landscape mode to useDevice hook
> landscape mode to useDevice hook

- src/components/AppLayout/Notifications/Notification.tsx
- src/components/AppLayout/Notifications/__test__/notification.spec.tsx
- src/components/AppLayout/Notifications/__test__/notifications.spec.tsx
- src/components/AppLayout/Notifications/index.tsx
- src/components/AppLayout/Notifications/types.ts
- stories/Notifications.stories.tsx
Adapt Notifications component for Bot announcements
> [BOT]maryia/BOT-2164/Adapt Notifications component for Bot announcements

- src/components/SectionMessage/SectionMessage.scss
- src/styles/abstracts/_variables.scss
- src/styles/base/_root.scss
Add dark support for text message:
> [FEQ] george / FEQ-2645 / Add dark support for text message

- .github/workflows/publish_npm_package.yml
- add storybook build step to the release workflow
> Shayan/Fix Storybook on production
